# Generated by Django 4.1.4 on 2022-12-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slugish'),
            preserve_default=False,
        ),
    ]
